language: go

go:
  - 1.5
  - 1.6.2

install:
  - # Testing
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/mock
  - # Logging
  - go get github.com/Sirupsen/logrus

